### GET CURRENT CONFIG
GET http://localhost:3000/api/arduino/config

### POST A CONFIG
POST http://localhost:3000/api/arduino/config
Content-Type: application/json

{
  "minutesPerCoin": 1,
  "maxPCs": 15
}