### GET ALL SESSIONS
GET http://localhost:8080/api/sessions/
Content-Type: application/json

### GET REMAINING TIME FOR PC
GET http://localhost:8080/api/sessions/3/remaining
Content-Type: application/json

### EXTEND TIME FROM API
POST http://localhost:8080/api/sessions/1/extend
Content-Type: application/json

{
  "minutes": 12,
  "source": "admin",
  "amount": 2
}